[package]
name = "full_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
pretty_ini = "0.1.6"
toml_edit = "0.19.3"